[package]
name = "krpc-api"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
tokio = { version = "1.18.2", features = ["full"] }
prost = "0.10.4"
bytes = "1.1.0"

[build-dependencies]
prost-build = "0.10.4"